AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31 # identifies as SAM template file
Description: AWS SAM for MEAN Project

Resources:
  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: quokka-submitted-reports
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true
      Tags:
        - Key: BatchID
          Value: SAM

  SusReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: quokka-sus-reports
      Tags:
        - Key: BatchID
          Value: SAM

  PDFReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: quokka-pdf
      Tags:
        - Key: BatchID
          Value: SAM

  QuokkaDetectSusFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: lambda/checksus/
      FunctionName: 'quokka-detect-sus-reports'
      Description: Detects suspicious materials. (SSN, credit card numbers)
      Role: arn:aws:iam::571600854971:role/QuokkaDetectSusFunctionRole
      Events:
        S3TriggerEvent:
          Type: S3
          Properties:
            Bucket:
              Ref: ReportBucket
            Events: s3:ObjectCreated:*

  QuokkaSubmitReportFunction:
      Type: 'AWS::Serverless::Function'
      Properties:
        Handler: index.handler
        Runtime: nodejs20.x
        CodeUri: lambda/submitreport/
        FunctionName: 'quokka-submit-report'
        Description: Submits report to s3 bucket.
        Role: arn:aws:iam::571600854971:role/QuokkaDetectSusFunctionRole
        Events:
          EventBridgeTriggerEvent:
            Type: EventBridgeRule
            Properties:
              Pattern: 
                source: ["aws.rds"] 
                detail-type: ["RDS DB Cluster Event"]
                detail:
                  eventName: ["INSERT"] # Match on INSERT operations
                  databaseName: ["pangolin-db"]
                  tableName: ["reports"] 

  QuokkaReportToPDFFunction:
        Type: 'AWS::Serverless::Function'
        Properties:
          Handler: index.handler
          Runtime: nodejs20.x
          CodeUri: lambda/generatereport/
          FunctionName: 'quokka-generate-pdf'
          Description: Generate pdf from report submission to database.
          Role: arn:aws:iam::571600854971:role/QuokkaDetectSusFunctionRole
          Events:
            APIGatewayTriggerEvent:
              Type: HttpApi 
              Properties:
                Path: /reporttopdf
                Method: post
